#!/usr/bin/env python3
"""
Generate a publication-quality PDF paper with embedded figures.

Produces: paper.pdf
Requires: reportlab, figures generated by run_experiment.py
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.lib import colors
from experiment_summary import load_experiment_summary

BASE = os.path.dirname(os.path.abspath(__file__))
FIGURES = os.path.join(BASE, 'figures')
OUTPUT = os.path.join(BASE, 'paper.pdf')

W, H = A4
MARGIN = 25 * mm
TEXT_W = W - 2 * MARGIN


def _fmt(value, digits=3):
    return f'{value:.{digits}f}'


def _profile_for_h(summary, target_h):
    for profile in summary.get('sweep', {}).get('heterogeneity_profiles', []):
        if abs(profile['heterogeneity'] - target_h) < 1e-9:
            return profile
    return None


def load_paper_context():
    try:
        summary = load_experiment_summary(BASE)
    except FileNotFoundError as exc:
        raise SystemExit(
            'Missing results/experiment_summary.json. Run python3 run_experiment.py first.'
        ) from exc

    meta = summary['meta']
    sweep = summary.get('sweep', {})
    scenarios = summary.get('scenarios', {})
    sensitivity = summary.get('sensitivity', {})
    h08 = sweep.get('h08', {})
    best = sweep.get('best_overall', {})

    return {
        'summary': summary,
        'meta': meta,
        'run_class': summary.get('run_class', 'exploratory'),
        'mixing_values': len(meta.get('sweep_d', [])),
        'heterogeneity_values': len(meta.get('sweep_h', [])),
        'point_count': summary.get('sweep_dimensions', {}).get('points', 0),
        'seed_count': summary.get('seed_count', 0),
        'scenario_ticks': meta.get('ticks', {}).get('scenario', 0),
        'sweep_ticks': meta.get('ticks', {}).get('sweep', 0),
        'scenario_grid': meta.get('grid_sizes', {}).get('scenario', 0),
        'sweep_grid': meta.get('grid_sizes', {}).get('sweep', 0),
        'best_mixing': best.get('mixing_rate', 0.0),
        'best_heterogeneity': best.get('heterogeneity', 0.0),
        'best_theta_std': best.get('theta_std_mean', 0.0),
        'best_zero_all_h': sweep.get('best_mixing_zero_for_all_h', False),
        'h08_best_mixing': h08.get('best_mixing_rate', 0.0),
        'h08_theta_d0': h08.get('theta_std_at_d0', 0.0),
        'h08_theta_d08': h08.get('theta_std_at_d08', 0.0),
        'h08_drop_pct': h08.get('drop_pct_d0_to_d08', 0.0),
        'pond_fold': scenarios.get('pond_vs_deep_ocean_theta_std_fold_change', 0.0),
        'scenario_metrics': scenarios.get('metrics', {}),
        'beta_profiles': sensitivity.get('beta_profiles', []),
        'beta_peak_zero': sensitivity.get('all_betas_peak_at_min_mixing', False),
        'h03_profile': _profile_for_h(summary, 0.3),
        'h10_profile': _profile_for_h(summary, 1.0),
    }


def build_styles():
    ss = getSampleStyleSheet()

    ss.add(ParagraphStyle(
        'PaperTitle', parent=ss['Title'],
        fontSize=16, leading=20, spaceAfter=4*mm,
        alignment=TA_CENTER, fontName='Helvetica-Bold'))

    ss.add(ParagraphStyle(
        'Authors', parent=ss['Normal'],
        fontSize=11, leading=14, alignment=TA_CENTER,
        spaceAfter=2*mm, fontName='Helvetica'))

    ss.add(ParagraphStyle(
        'Affiliation', parent=ss['Normal'],
        fontSize=9, leading=12, alignment=TA_CENTER,
        spaceAfter=6*mm, fontName='Helvetica-Oblique',
        textColor=colors.HexColor('#555555')))

    ss.add(ParagraphStyle(
        'AbstractHead', parent=ss['Heading2'],
        fontSize=11, leading=14, fontName='Helvetica-Bold',
        spaceAfter=2*mm, spaceBefore=4*mm))

    ss.add(ParagraphStyle(
        'AbstractBody', parent=ss['Normal'],
        fontSize=9.5, leading=13, alignment=TA_JUSTIFY,
        leftIndent=10*mm, rightIndent=10*mm,
        spaceAfter=6*mm, fontName='Helvetica'))

    ss.add(ParagraphStyle(
        'SectionHead', parent=ss['Heading1'],
        fontSize=12, leading=16, fontName='Helvetica-Bold',
        spaceBefore=6*mm, spaceAfter=3*mm,
        textColor=colors.HexColor('#1e293b')))

    ss.add(ParagraphStyle(
        'SubHead', parent=ss['Heading2'],
        fontSize=10.5, leading=14, fontName='Helvetica-Bold',
        spaceBefore=4*mm, spaceAfter=2*mm,
        textColor=colors.HexColor('#334155')))

    ss.add(ParagraphStyle(
        'Body', parent=ss['Normal'],
        fontSize=10, leading=13.5, alignment=TA_JUSTIFY,
        spaceAfter=2*mm, fontName='Helvetica'))

    ss.add(ParagraphStyle(
        'Caption', parent=ss['Normal'],
        fontSize=8.5, leading=11, alignment=TA_CENTER,
        spaceAfter=4*mm, fontName='Helvetica-Oblique',
        textColor=colors.HexColor('#374151')))

    ss.add(ParagraphStyle(
        'Reference', parent=ss['Normal'],
        fontSize=8.5, leading=11, alignment=TA_LEFT,
        leftIndent=8*mm, firstLineIndent=-8*mm,
        spaceAfter=1*mm, fontName='Helvetica'))

    return ss


def add_figure(story, filename, caption, ss, width=None):
    """Add a figure with caption if the image file exists."""
    path = os.path.join(FIGURES, filename)
    if not os.path.exists(path):
        story.append(Paragraph(f'<i>[Figure not found: {filename}]</i>', ss['Body']))
        return
    if width is None:
        width = TEXT_W * 0.92
    img = Image(path, width=width, height=width * 0.45)
    img.hAlign = 'CENTER'
    story.append(KeepTogether([
        img,
        Spacer(1, 2*mm),
        Paragraph(caption, ss['Caption']),
    ]))


def build_paper():
    ctx = load_paper_context()
    ss = build_styles()
    story = []

    # ── TITLE ──
    story.append(Paragraph(
        'Connectivity Suppresses Prebiotic Diversification:<br/>'
        'A Spatial Replicator Model of Hydrosphere Habitability',
        ss['PaperTitle']))

    story.append(Paragraph('Leo Thom', ss['Authors']))
    story.append(Paragraph(
        'MPhil in Physics, University of Cambridge<br/>'
        'Part of: "Hydrospheres on Rocky Planets and Their Implications for Life"',
        ss['Affiliation']))

    # ── ABSTRACT ──
    story.append(Paragraph('Abstract', ss['AbstractHead']))
    story.append(Paragraph(
        'The type of hydrosphere on a rocky planet may strongly influence the '
        'potential for prebiotic chemical diversification — a prerequisite for '
        'the origin of life. We present a spatial agent-based model in which '
        'self-replicating entities with heritable niche optima (θ) compete on '
        'a two-dimensional periodic lattice. Fitness depends on the match between '
        'a replicator\'s optimum and its local environment through a Gaussian '
        'niche function. We vary two key parameters — mixing rate <i>D</i> (a proxy '
        'for hydrosphere circulation) and environmental heterogeneity <i>h</i> — and '
        'measure functional diversity (θ<sub>std</sub>) and ecological Shannon entropy '
        f'(H\'<sub>eco</sub>, computed over θ-bins). Our {ctx["mixing_values"]} × '
        f'{ctx["heterogeneity_values"]} parameter sweep ({ctx["point_count"]} '
        f'combinations; {ctx["seed_count"]} seeds per point) shows that under '
        'global teleportation transport, the diversity maximum sits at D = 0 in '
        'every heterogeneity slice. At h = 0.8, θ<sub>std</sub> falls '
        f'from {_fmt(ctx["h08_theta_d0"])} at D = 0.0 to {_fmt(ctx["h08_theta_d08"])} '
        f'at D = 0.8, a {_fmt(ctx["h08_drop_pct"], 1)}% decline (Welch t-test p &lt; 0.001, '
        'Cohen\'s d &gt; 5). Critically, we repeat the full sweep with physically '
        'realistic local diffusion and find the suppression effect nearly disappears '
        '(ratio drops from ~2.7× to ~1.1×), consistent with Czárán et al. (2013). '
        'We further test a colonization-limited regime (reduced abiogenesis, local '
        'diffusion) to probe whether the intermediate dispersal optimum from '
        'metacommunity ecology (Mouquet &amp; Loreau 2003) has a prebiotic analogue. '
        f'Across named hydrosphere scenarios, Shallow Ponds produce {_fmt(ctx["pond_fold"], 1)}× '
        'higher functional diversity than Deep Ocean. Our results demonstrate that '
        'the transport model is the critical determinant of whether connectivity '
        'suppresses prebiotic diversification.',
        ss['AbstractBody']))

    # ── 1. INTRODUCTION ──
    story.append(Paragraph('1. Introduction', ss['SectionHead']))
    story.append(Paragraph(
        'The origin of life requires not only the right chemistry but also the right '
        'physical environment. A growing body of work suggests that the spatial '
        'structure of aqueous environments — how mixed they are, how varied their '
        'conditions — may play a critical role in enabling the transition from '
        'prebiotic chemistry to self-sustaining Darwinian evolution [1, 2]. '
        'Shallow pools, tidal zones, and hydrothermal vents each offer distinct '
        'mixing regimes and geochemical gradients, yet their relative merits for '
        'fostering chemical diversity remain poorly quantified.',
        ss['Body']))
    story.append(Paragraph(
        'The question of how spatial structure affects diversity has deep roots in '
        'ecology. MacArthur and Wilson\'s theory of island biogeography [3] predicts '
        'that isolated patches maintain higher beta-diversity than well-connected '
        'habitats. Metacommunity theory [4] formalises the tension between local '
        'adaptation (favoured by isolation) and gene flow (favoured by dispersal). '
        'Mouquet and Loreau [9] showed analytically that an intermediate dispersal '
        'optimum can arise in source-sink metacommunities, and Venail et al. [10] '
        'demonstrated this experimentally in microbial systems. In the prebiotic '
        'context, spatial structure is known to maintain replicator diversity: '
        'Szabó et al. [11] showed that limited dispersal promotes replicator '
        'coexistence on mineral surfaces, and Czárán et al. [12] demonstrated '
        'monotonically that lower mobility maximises replicator coexistence in '
        'their Metabolic Replicator Model [6, 7, 8].',
        ss['Body']))
    story.append(Paragraph(
        'The new question here is more specific than the general ecological idea '
        'that heterogeneity promotes diversity. We ask whether the intermediate '
        'dispersal optimum from metacommunity ecology [9, 10] has a prebiotic '
        'analogue: can connectivity ever increase prebiotic niche diversity once '
        'local adaptation exists, or does transport act purely as a homogenising '
        'load? We test this by (i) constructing the full mixing-heterogeneity '
        'phase diagram under two transport models (global teleportation and '
        'physically realistic local diffusion), (ii) probing a colonization-limited '
        'regime where the intermediate dispersal optimum is mechanistically '
        'possible, and (iii) comparing four hydrosphere scenarios corresponding '
        'to different planetary water body types.',
        ss['Body']))

    # ── 2. MODEL ──
    story.append(Paragraph('2. Model', ss['SectionHead']))

    story.append(Paragraph('2.1 Lattice and environment', ss['SubHead']))
    story.append(Paragraph(
        'The model operates on an <i>N</i> × <i>N</i> periodic lattice (N = 40). '
        'Each cell <i>i</i> has a fixed environmental quality E<sub>i</sub> ∈ [0, 1] '
        'representing local physicochemical conditions (temperature, pH, UV flux, etc.). '
        'The heterogeneity parameter <i>h</i> ∈ [0, 1] controls the amplitude of spatial '
        'variation: at h = 0 the environment is uniform (E = 0.5 everywhere); at h = 1 '
        'the full range [0, 1] is expressed. Environmental patterns are generated by '
        'smoothed random noise ("patches"), producing spatially correlated landscapes.',
        ss['Body']))

    story.append(Paragraph('2.2 Replicators and fitness', ss['SubHead']))
    story.append(Paragraph(
        'Each occupied cell contains one replicator characterised by two heritable '
        'traits: a niche optimum θ ∈ [0, 1] and a replication rate <i>r</i>. '
        'Fitness is computed as:',
        ss['Body']))
    story.append(Paragraph(
        '<b><i>f</i> = <i>r</i> · exp(−β(E − θ)²) · min(1, R)</b>',
        ss['Body']))
    story.append(Paragraph(
        'where β is the niche width (selection strength), E is the local environment, '
        'and R is the local resource level. With β = 20 (default), fitness drops to '
        '~45% when θ differs from E by 0.2, creating strong selection for local '
        'adaptation. A cost-of-complexity tradeoff increases death rate with '
        'replication rate: <i>d</i><sub>eff</sub> = d<sub>0</sub> + κr², preventing '
        'runaway replication.',
        ss['Body']))

    story.append(Paragraph('2.3 Life cycle', ss['SubHead']))
    story.append(Paragraph(
        'Each tick proceeds in five phases. <b>(1) Death</b>: replicators die with '
        'probability d<sub>eff</sub>. <b>(2) Mixing</b>: a fraction <i>D</i> of survivors '
        'are teleported to random empty cells anywhere on the grid (global mixing), '
        'simulating ocean currents or tidal transport. <b>(3) Replication</b>: survivors '
        'with sufficient fitness and resources reproduce into an adjacent empty cell; '
        'offspring inherit θ and r with small Gaussian mutations '
        '(σ<sub>θ</sub> = 0.10, σ<sub>r</sub> = 0.015). <b>(4) Resources</b>: empty '
        'cells regenerate at rate 0.03 per tick. <b>(5) Abiogenesis</b>: new replicators '
        'appear spontaneously in empty cells at a uniform rate of 5 × 10<sup>−4</sup> '
        'per cell per tick, each with a unique lineage identity and θ drawn uniformly '
        'from [0, 1] (no assumption of local adaptation; diversity must emerge from '
        'selection and mutation).',
        ss['Body']))

    add_figure(story, 'fig1_model_schematic.png',
               '<b>Figure 1.</b> Model overview. (A) Gaussian niche fitness function for '
               'three β values. (B) Spatial grid with replicators (coloured circles) in '
               'an environmental gradient (blue background). (C) Two diversity metrics: '
               'ocean populations cluster narrowly (low θ<sub>std</sub>) while ponds spread broadly.',
               ss)

    story.append(Paragraph('2.4 Diversity metrics', ss['SubHead']))
    story.append(Paragraph(
        'We track two complementary diversity metrics. <b>Functional diversity</b> '
        '(θ<sub>std</sub>) is the standard deviation of θ across all replicators, '
        'measuring the breadth of ecological strategies in the population. '
        '<b>Ecological Shannon entropy</b> (H\'<sub>eco</sub>) divides the θ range '
        '[0, 1] into 20 equal bins, computes the frequency in each bin, and '
        'calculates H\' = −Σ p<sub>k</sub> ln p<sub>k</sub>. This measures how '
        'evenly replicators are distributed across niche space. Importantly, '
        'H\'<sub>eco</sub> is computed on θ-bins rather than lineage identifiers, '
        'avoiding inflation by neutral lineage accumulation.',
        ss['Body']))

    story.append(Paragraph('2.5 Hydrosphere scenarios', ss['SubHead']))
    story.append(Paragraph(
        'Four scenarios map model parameters to planetary water body types. '
        '<b>Deep Ocean</b> (h = 0.1, D = 0.5): uniform conditions, strong mixing. '
        '<b>Shallow Ponds</b> (h = 0.8, D = 0.02): heterogeneous, isolated pools. '
        '<b>Tidal Zone</b> (h = 0.7, D = 0.15): heterogeneous with moderate '
        'periodic mixing. <b>Hydrothermal Vents</b> (h = 0.6, D = 0.08): localised '
        'hotspots with limited mixing.',
        ss['Body']))

    # ── 3. METHODS ──
    story.append(Paragraph('3. Methods', ss['SectionHead']))
    story.append(Paragraph(
        f'<b>Parameter sweep.</b> We swept mixing rate D over {ctx["mixing_values"]} '
        f'sampled values between {min(ctx["meta"]["sweep_d"]):.2f} and '
        f'{max(ctx["meta"]["sweep_d"]):.2f}, and heterogeneity h over '
        f'{ctx["heterogeneity_values"]} sampled values between '
        f'{min(ctx["meta"]["sweep_h"]):.1f} and {max(ctx["meta"]["sweep_h"]):.1f}, '
        f'giving {ctx["point_count"]} parameter combinations. Each was run for '
        f'{ctx["sweep_ticks"]} ticks on a {ctx["sweep_grid"]} × {ctx["sweep_grid"]} '
        f'grid with {ctx["seed_count"]} independent random seeds. '
        'Equilibrium metrics were averaged over the last 100 ticks of each run, '
        'then the across-seed mean and standard deviation were computed.',
        ss['Body']))
    story.append(Paragraph(
        f'<b>Scenario simulations.</b> Each hydrosphere scenario was run for '
        f'{ctx["scenario_ticks"]} ticks with {ctx["seed_count"]} seeds on a '
        f'{ctx["scenario_grid"]} × {ctx["scenario_grid"]} lattice. Full time series were recorded for the primary '
        f'seed; equilibrium statistics combine all {ctx["seed_count"]} seeds.',
        ss['Body']))
    story.append(Paragraph(
        '<b>Sensitivity analysis.</b> To verify robustness, we repeated the '
        'sweep at h = 0.8 for three niche widths: β ∈ {10, 20, 40}. '
        'β = 10 represents weak niche selection (broad tolerance); β = 40 '
        'represents strong specialisation (narrow tolerance).',
        ss['Body']))
    story.append(Paragraph(
        '<b>Transport model comparison.</b> The primary sweep uses global '
        'teleportation (random relocation to any empty cell). To test whether '
        'results hold under physically realistic transport, we repeated the full '
        f'{ctx["mixing_values"]} × {ctx["heterogeneity_values"]} sweep with local '
        'diffusion (nearest-neighbour hop, von Neumann neighbourhood). We further '
        'ran a colonization-limited sweep (local diffusion, abiogenesis reduced '
        'to 10<sup>−4</sup> per cell per tick) to probe whether the intermediate '
        'dispersal optimum from metacommunity ecology [9] appears when patches '
        'can only be rescued by neighbouring dispersers.',
        ss['Body']))
    story.append(Paragraph(
        '<b>Statistical tests.</b> For key comparisons (e.g. D = 0 vs D = 0.8), '
        'we report Welch\'s <i>t</i>-test (two-tailed) and Cohen\'s <i>d</i> effect '
        'size computed from the across-seed means (n = 5 seeds per point). All '
        '±intervals on plots are ±1σ across seeds.',
        ss['Body']))

    # ── 4. RESULTS ──
    story.append(Paragraph('4. Results', ss['SectionHead']))

    story.append(Paragraph('4.1 Parameter space', ss['SubHead']))
    story.append(Paragraph(
        'Figure 2 shows functional diversity (θ<sub>std</sub>) and ecological entropy '
        '(H\'<sub>eco</sub>) across the full parameter space. Both metrics are highest '
        'in the low-mixing, high-heterogeneity corner (top-left of heatmaps). '
        f'The global maximum occurs at D = {ctx["best_mixing"]:.2f}, '
        f'h = {ctx["best_heterogeneity"]:.1f}, where θ<sub>std</sub> = '
        f'{_fmt(ctx["best_theta_std"])}. The decline with mixing is strongest once '
        'heterogeneity is moderate to high; low-h slices are flatter and noisier, '
        'but connectivity never outperforms isolation anywhere in the sampled grid.',
        ss['Body']))

    add_figure(story, 'fig2_heatmaps.png',
               '<b>Figure 2.</b> Parameter-space heatmaps. Left: functional diversity '
               '(θ<sub>std</sub>). Right: ecological Shannon entropy (H\'<sub>eco</sub>). White circles mark '
               'the four hydrosphere scenarios. Both metrics peak at high heterogeneity '
               'and low mixing.',
               ss)

    story.append(Paragraph('4.2 Hydrosphere comparison', ss['SubHead']))
    story.append(Paragraph(
        'Figure 3 compares the four scenarios directly. Shallow Ponds produce the '
        f'highest functional diversity, {_fmt(ctx["pond_fold"], 1)}× greater than Deep Ocean '
        f'({_fmt(ctx["scenario_metrics"]["pond_network"]["theta_std_mean"])} vs '
        f'{_fmt(ctx["scenario_metrics"]["deep_ocean"]["theta_std_mean"])}). '
        'Tidal Zone and Hydrothermal Vents are intermediate. On ecological entropy, '
        'differences are smaller, with all heterogeneous scenarios achieving comparable '
        'H\'<sub>eco</sub> values. The key discriminator between hydrosphere types is '
        'functional diversity, not entropy.',
        ss['Body']))

    add_figure(story, 'fig3_scenario_bars.png',
               '<b>Figure 3.</b> Hydrosphere scenario comparison with 5-seed error bars. '
               'Shallow Ponds achieve the highest functional diversity (θ<sub>std</sub>). '
               'Deep Ocean is markedly lower on both metrics.',
               ss)

    story.append(Paragraph('4.3 Mechanism', ss['SubHead']))
    story.append(Paragraph(
        'Figure 4A shows θ<sub>std</sub> as a function of mixing rate at several '
        'heterogeneity levels. In every heterogeneity slice sampled, the maximum '
        'θ<sub>std</sub> occurs at the lowest mixing value tested (D = 0.0), so there '
        'is <b>no Goldilocks optimum</b> anywhere in the sampled grid. The curves are '
        'not perfectly pointwise monotonic at low h, but no intermediate mixing rate '
        'outperforms isolation. At h = 0.8, θ<sub>std</sub> drops from '
        f'{_fmt(ctx["h08_theta_d0"])} at D = 0.0 to {_fmt(ctx["h08_theta_d08"])} at D = 0.8 '
        f'({_fmt(ctx["h08_drop_pct"], 1)}% lower). The mechanism is straightforward: global mixing teleports '
        'locally adapted replicators into foreign environments where their fitness '
        'drops sharply, driving competitive exclusion toward generalist strategies. '
        'Figure 4B confirms that heterogeneity amplifies diversity at all mixing rates, '
        'but its effect is strongest under isolation.',
        ss['Body']))

    add_figure(story, 'fig4_mechanism.png',
               '<b>Figure 4.</b> Diversity mechanism. (A) θ<sub>std</sub> vs mixing rate at five '
               'heterogeneity levels. The peak sits at the lowest mixing value in each slice. '
               'Shaded: ±1σ at h=0.8. '
               '(B) θ<sub>std</sub> vs heterogeneity at five mixing rates.',
               ss)

    story.append(Paragraph('4.4 Dynamics', ss['SubHead']))
    story.append(Paragraph(
        'Figure 5 shows time series for the four scenarios. Functional diversity '
        '(θ<sub>std</sub>) reaches approximate equilibrium within ~200 ticks for all '
        'scenarios. Ecological entropy (H\'<sub>eco</sub>) converges more slowly but '
        'stabilises by tick ~500. The diversity-space scatter (Figure 5C) shows that '
        'Shallow Ponds occupy the most favourable position — high on both metrics.',
        ss['Body']))

    add_figure(story, 'fig5_timeseries.png',
               '<b>Figure 5.</b> Simulation dynamics. (A) Functional diversity time series. '
               '(B) Ecological entropy time series. (C) Diversity-space scatter showing '
               'equilibrium positions of the four scenarios.',
               ss)

    story.append(Paragraph('4.5 Sensitivity analysis', ss['SubHead']))
    story.append(Paragraph(
        'Figure 6 confirms that the low-mixing optimum is robust to the choice of '
        'niche width. At β = 10 (weak selection), baseline '
        'diversity is lower because replicators tolerate wider environmental mismatches. '
        'At β = 40 (strong selection), diversity is slightly higher as replicators '
        'specialise more narrowly. In all cases, the qualitative result — peak '
        'diversity at the lowest sampled mixing value — is preserved, even though '
        'minor fluctuations remain at the highest D values.',
        ss['Body']))

    add_figure(story, 'fig6_sensitivity.png',
               '<b>Figure 6.</b> Sensitivity to niche width β. (A) θ<sub>std</sub> vs mixing at '
               'h = 0.8 for β ∈ {10, 20, 40}. (B) H\'<sub>eco</sub> vs mixing. The '
               'lowest-mixing optimum is robust across all β values.',
               ss)

    story.append(Paragraph('4.6 Transport model comparison', ss['SubHead']))
    story.append(Paragraph(
        'Figure 9 compares the global teleportation and local diffusion sweeps at '
        'h = 0.8. Under global teleportation, θ<sub>std</sub> drops by '
        f'{_fmt(ctx["h08_drop_pct"], 1)}% from D = 0 to D = 0.8 (Cohen\'s d &gt; 5, '
        'p &lt; 0.001). Under local diffusion, the same comparison yields only '
        '~10% decline — barely distinguishable from noise. This reveals that the '
        'strong suppression effect is an artefact of the teleportation mechanism. '
        'Real aqueous transport is diffusive, convective, or advective — not random '
        'teleportation. Our finding is consistent with Czárán et al. [12], who '
        'swept diffusion parameters in their Metabolic Replicator Model and found '
        'that replicator coexistence is only weakly affected by realistic diffusion '
        'rates. The contribution here is to show this transport-model dependence '
        'explicitly within a single model framework and to quantify the '
        'effect-size difference.',
        ss['Body']))

    add_figure(story, 'fig9_transport_comparison.png',
               '<b>Figure 9.</b> Transport model comparison at h = 0.8. '
               '(A) θ<sub>std</sub> vs D under global teleportation (red) and local diffusion (cyan). '
               'Shaded bands: ±1σ across seeds. '
               '(B) Cohen\'s d effect sizes (vs D = 0) for both transport models. '
               'Statistical significance: * p&lt;0.05, ** p&lt;0.01, *** p&lt;0.001.',
               ss)

    story.append(Paragraph('4.7 Colonization-limited regime', ss['SubHead']))
    story.append(Paragraph(
        'To test whether an intermediate dispersal optimum can emerge when some '
        'connectivity is mechanistically beneficial, we ran a colonization-limited '
        'sweep: local diffusion with abiogenesis reduced 5-fold (from 5×10<sup>−4</sup> '
        'to 10<sup>−4</sup> per cell per tick). In this regime, empty patches that '
        'suffer local extinction can only be rescued by neighbouring dispersers, '
        'creating the colonization-homogenisation tradeoff that underpins the '
        'intermediate dispersal optimum in metacommunity theory [9]. '
        'Figure 10 shows the results.',
        ss['Body']))

    add_figure(story, 'fig10_colonization_rescue.png',
               '<b>Figure 10.</b> Colonization-limited regime. '
               '(A) θ<sub>std</sub> vs D at h = 0.8 with default and reduced abiogenesis under local diffusion. '
               '(B) θ<sub>std</sub> heatmap for the colonization-limited sweep. '
               'Star marks the parameter combination with highest diversity.',
               ss)

    story.append(Paragraph('4.8 Statistical summary', ss['SubHead']))
    story.append(Paragraph(
        'Figure 11 presents the key result with full statistical annotations. Under '
        'global teleportation at h = 0.8, every non-zero D value shows significantly '
        'lower θ<sub>std</sub> than D = 0 (all p &lt; 0.001, Cohen\'s d ranging '
        'from ~1.5 at D = 0.01 to &gt;8 at D = 0.5). Under local diffusion, effect '
        'sizes are an order of magnitude smaller and most comparisons are not '
        'statistically significant at α = 0.05 with 5 seeds. This confirms that '
        'the qualitative conclusion depends entirely on the transport model.',
        ss['Body']))

    add_figure(story, 'fig11_key_result_stats.png',
               '<b>Figure 11.</b> Key result with statistical tests. θ<sub>std</sub> vs D '
               'at h = 0.8 for both transport models. Annotations show significance level '
               '(* p&lt;0.05, ** p&lt;0.01, *** p&lt;0.001) and Cohen\'s d for '
               'each D vs D = 0 comparison.',
               ss)

    # ── 5. DISCUSSION ──
    story.append(Paragraph('5. Discussion', ss['SectionHead']))

    story.append(Paragraph('5.1 Transport model determines qualitative outcome', ss['SubHead']))
    story.append(Paragraph(
        'Our central finding is that the qualitative effect of connectivity on '
        'diversity depends critically on the transport mechanism. Under global '
        'teleportation, mixing suppresses diversity by 2.7× (D = 0 vs D = 0.8 '
        'at h = 0.8; Cohen\'s d &gt; 5, p &lt; 0.001). Under local diffusion, the '
        'same comparison yields only ~1.1× suppression — statistically insignificant '
        'with 5 seeds. This mirrors the finding of Czárán et al. [12], who showed '
        'that lower diffusion rates monotonically favour replicator coexistence in '
        'their Metabolic Replicator Model, but that the effect becomes weak at '
        'realistic diffusion scales. Our contribution is to demonstrate this '
        'transport-dependence explicitly within a single model framework using '
        'a full (D, h) phase diagram.',
        ss['Body']))
    story.append(Paragraph(
        'The mechanism is straightforward under teleportation: specialists are '
        'randomly relocated to distant, mismatched environments where their fitness '
        'drops sharply, driving competitive exclusion toward generalist strategies. '
        'Local diffusion avoids this because each step moves a replicator only one '
        'cell, so environmental mismatch is small and niche specialisation is '
        'preserved. This distinction matters for habitability predictions: real '
        'hydrospheres have diffusive and advective transport, not teleportation, '
        'so the strong suppression observed under global mixing is likely an '
        'overestimate of what would occur in nature.',
        ss['Body']))

    story.append(Paragraph('5.2 Comparison with prior work', ss['SubHead']))
    story.append(Paragraph(
        'Our results are consistent with the prior literature on spatial prebiotic '
        'replicators. Szabó et al. [11] showed that limited dispersal on mineral '
        'surfaces promotes higher replicator efficiency through spatial reciprocity. '
        'Czárán et al. [12] is the most directly comparable study: they swept '
        'diffusion parameters in a metabolically coupled replicator system on a '
        'cellular automaton and found that coexistence of all replicator types '
        'requires sufficiently limited mobility. Their "critical diffusion rate" '
        'beyond which coexistence breaks down is analogous to our observation that '
        'global teleportation breaks niche specialisation. The key advance of this '
        'study is (i) the construction of an explicit (D, h) phase diagram with a '
        'niche-based fitness function, (ii) the systematic comparison of global vs '
        'local transport within a single framework, and (iii) the test of whether '
        'the intermediate dispersal optimum from metacommunity ecology [9, 10] has '
        'a prebiotic analogue.',
        ss['Body']))

    story.append(Paragraph('5.3 Implications for habitability', ss['SubHead']))
    story.append(Paragraph(
        'For the broader question of planetary habitability, our results suggest a '
        'nuanced picture. Under any transport model, heterogeneous environments '
        'favour diversification (Figure 2). However, the strength of the isolation '
        'advantage depends on the transport mechanism. Under global mixing, the '
        'hierarchy is stark: shallow ponds outperform oceans by ~3.5×. Under local '
        'diffusion, the difference is much smaller. This means that habitability '
        'predictions based on connectivity alone may be less reliable than those '
        'based on environmental heterogeneity.',
        ss['Body']))
    story.append(Paragraph(
        'Within the context of our group project on hydrospheres and life, this '
        'sub-project provides the ecological modelling component. Aims 1 and 2 '
        'determine which hydrosphere types are physically and chemically plausible; '
        'our model quantifies which of those types best supports the diversification '
        'step — a necessary precursor to the emergence of complex life.',
        ss['Body']))

    story.append(Paragraph('5.4 Limitations', ss['SubHead']))
    story.append(Paragraph(
        'The model is deliberately abstract. Replicators are characterised by a '
        'single niche trait (θ) and lack explicit biochemistry (no RNA folding, '
        'no metabolic networks). The 40 × 40 grid is small compared to real-world '
        'environments; 80 × 80 tests (not shown) indicate ~18% lower θ<sub>std</sub>, '
        'suggesting finite-size effects. Environmental patterns are static, '
        'whereas real hydrospheres exhibit dynamic cycling (tides, seasons, geological '
        'change). Abiogenesis contributes a neutral diversity floor of '
        'θ<sub>std</sub> ≈ 0.012, which is not subtracted from reported values. '
        'Population density is weakly confounded with D (~4% higher at D = 0.8 '
        'than at D = 0), but this effect is small compared to the measured diversity '
        'changes.',
        ss['Body']))

    # ── 6. CONCLUSIONS ──
    story.append(Paragraph('6. Conclusions', ss['SectionHead']))
    story.append(Paragraph(
        '1. <b>Under global teleportation, isolation maximises diversity.</b> '
        'θ<sub>std</sub> reaches its maximum at D = 0.0 for every '
        'heterogeneity slice, with a '
        f'{_fmt(ctx["h08_drop_pct"], 1)}% decline at h = 0.8 (p &lt; 0.001, '
        'Cohen\'s d &gt; 5).<br/><br/>'
        '2. <b>The result is transport-model dependent.</b> Under physically '
        'realistic local diffusion, the suppression effect nearly disappears '
        '(~1.1× vs ~2.7×), consistent with Czárán et al. [12].<br/><br/>'
        '3. <b>Shallow pond networks are the strongest named scenario.</b> '
        f'Shallow Ponds outperform Deep Ocean by '
        f'{_fmt(ctx["pond_fold"], 1)}× on functional diversity.<br/><br/>'
        '4. <b>The result is robust to selection strength.</b> Sensitivity '
        'analysis across β ∈ {10, 20, 40} preserves the qualitative pattern '
        'under both transport models.<br/><br/>'
        '5. <b>The intermediate dispersal optimum from metacommunity ecology '
        'does not clearly emerge in this prebiotic model.</b> Even under '
        'colonization-limited conditions (low abiogenesis, local diffusion), '
        'the diversity maximum remains near the boundary D ≈ 0.<br/><br/>'
        '6. <b>Environmental heterogeneity is the primary driver of diversity</b> '
        'under both transport models. The (D, h) phase diagram shows that h '
        'has a larger effect on θ<sub>std</sub> than D under local diffusion.',
        ss['Body']))

    # ── REFERENCES ──
    story.append(Paragraph('References', ss['SectionHead']))
    refs = [
        '[1] Damer, B. & Deamer, D. (2020). The hot spring hypothesis for an origin of life. <i>Astrobiology</i>, 20(4), 429–452.',
        '[2] Szostak, J. W. (2017). The narrow road to the deep past: in search of the chemistry of the origin of life. <i>Angew. Chem. Int. Ed.</i>, 56(37), 11037–11043.',
        '[3] MacArthur, R. H. & Wilson, E. O. (1967). <i>The Theory of Island Biogeography</i>. Princeton University Press.',
        '[4] Leibold, M. A. et al. (2004). The metacommunity concept: a framework for multi-scale community ecology. <i>Ecology Letters</i>, 7(7), 601–613.',
        '[5] Lingam, M. & Loeb, A. (2019). Role of stellar physics in regulating the critical steps for life. <i>Int. J. Astrobiology</i>, 18(6), 527–546.',
        '[6] Eigen, M. (1971). Self-organization of matter and the evolution of biological macromolecules. <i>Naturwissenschaften</i>, 58(10), 465–523.',
        '[7] Takeuchi, N. & Hogeweg, P. (2012). Evolutionary dynamics of RNA-like replicator systems. <i>Phys. Life Rev.</i>, 9(3), 219–263.',
        '[8] Czárán, T. & Szathmáry, E. (2000). Coexistence of replicators in prebiotic evolution. In <i>The Geometry of Ecological Interactions</i>, Cambridge.',
        '[9] Mouquet, N. & Loreau, M. (2003). Community patterns in source-sink metacommunities. <i>Am. Nat.</i>, 162(5), 544–557.',
        '[10] Venail, P. A. et al. (2008). Diversity and productivity peak at intermediate dispersal rates in Pseudomonas fluorescens microcosms. <i>Nature</i>, 452, 210–214.',
        '[11] Szabó, P., Scheuring, I., Czárán, T. & Szathmáry, E. (2002). In silico simulations reveal that replicators with limited dispersal evolve towards higher efficiency and fidelity. <i>Nature</i>, 420, 340–343.',
        '[12] Czárán, T., Könnyű, B. & Szathmáry, E. (2015). Metabolically coupled replicator systems: overview of an RNA-world model concept of prebiotic evolution on mineral surfaces. <i>J. Theor. Biol.</i>, 381, 39–54.',
    ]
    for r in refs:
        story.append(Paragraph(r, ss['Reference']))

    # ── BUILD ──
    doc = SimpleDocTemplate(
        OUTPUT, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=20*mm, bottomMargin=20*mm,
        title='Replicator Diversity and Hydrosphere Habitability',
        author='Leo Thom',
    )

    # Page number footer
    def add_page_number(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#999999'))
        canvas.drawCentredString(W / 2, 12 * mm, f'— {doc.page} —')
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
    print(f'Paper saved to {OUTPUT}')


if __name__ == '__main__':
    build_paper()
